# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: CI

on: [push]

jobs:
  check_dawn:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - job_name: "dev store, custom app login"
            store: tomorrow-plus-demo.myshopify.com
            password: DEV_PASSWORD
            collection_handle: SHOP_COLLECTION_HANDLE
            product_handle: SHOP_PRODUCT_HANDLE

          - job_name: "dev store, private app login"
            store: tomorrow-plus-demo.myshopify.com
            password: DEV_PASSWORD
            collection_handle: SHOP_COLLECTION_HANDLE
            product_handle: SHOP_PRODUCT_HANDLE

    name: ${{ matrix.job_name }}

    steps:
      - uses: actions/checkout@v3

      - name: Lighthouse CI action
        uses: ./
        id: lighthouse-ci-action
        with:
          store: ${{ matrix.store }}
          password: ${{ secrets[matrix.password] }}
          collection_handle: ${{ secrets[matrix.collection_handle] }}
          product_handle: ${{ secrets[matrix.product_handle] }}
          lhci_min_score_performance: 0.1
          lhci_min_score_accessibility: 0.1
